# Generated by Django 3.1 on 2020-12-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypharma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='medo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pi')),
            ],
        ),
    ]
